services:
  web:
    build: .
    container_name: park-note
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: park-note-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ./.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    driver: local

networks:
  default:
    name: park-note-network
